# Generated by Django 6.0.4 on 2026-05-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberVerse', models.SmallIntegerField(default=0)),
                ('ContentVerse', models.CharField(max_length=1000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chapter')),
            ],
        ),
    ]
