# Generated by Django 6.0.4 on 2026-05-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='IncompletePhrase',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
