# Generated by Django 6.0.4 on 2026-05-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_verse_incompletephrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='IncompletePhrase',
        ),
    ]
